// Code generated by MockGen. DO NOT EDIT.
// Source: aws_util/aws_util.go

// Package mock_aws_util is a generated GoMock package.
package mock_aws_util

import (
	reflect "reflect"
	error "social-alarm-service/error"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockAWSUtil is a mock of AWSUtil interface.
type MockAWSUtil struct {
	ctrl     *gomock.Controller
	recorder *MockAWSUtilMockRecorder
}

// MockAWSUtilMockRecorder is the mock recorder for MockAWSUtil.
type MockAWSUtilMockRecorder struct {
	mock *MockAWSUtil
}

// NewMockAWSUtil creates a new mock instance.
func NewMockAWSUtil(ctrl *gomock.Controller) *MockAWSUtil {
	mock := &MockAWSUtil{ctrl: ctrl}
	mock.recorder = &MockAWSUtilMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAWSUtil) EXPECT() *MockAWSUtilMockRecorder {
	return m.recorder
}

// DeleteObject mocks base method.
func (m *MockAWSUtil) DeleteObject(ctx *gin.Context, bucketName, key string) *error.ASError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, bucketName, key)
	ret0, _ := ret[0].(*error.ASError)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockAWSUtilMockRecorder) DeleteObject(ctx, bucketName, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockAWSUtil)(nil).DeleteObject), ctx, bucketName, key)
}

// UploadObject mocks base method.
func (m *MockAWSUtil) UploadObject(ctx *gin.Context, fileName, bucketName, key string) *error.ASError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadObject", ctx, fileName, bucketName, key)
	ret0, _ := ret[0].(*error.ASError)
	return ret0
}

// UploadObject indicates an expected call of UploadObject.
func (mr *MockAWSUtilMockRecorder) UploadObject(ctx, fileName, bucketName, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadObject", reflect.TypeOf((*MockAWSUtil)(nil).UploadObject), ctx, fileName, bucketName, key)
}
